fixtures:
  forge_modules:
    stdlib:       "puppetlabs/stdlib"
    java:         "puppetlabs/java"
    yumrepo_core: "puppetlabs/yumrepo_core"
    wget:         "puppet/wget"
  symlinks:
    artifactory:  "#{source_dir}"
