fixtures:
  forge_modules:
    augeas:       "puppetlabs/augeas_core"
    stdlib:       "puppetlabs/stdlib"
    java:         "puppetlabs/java"
    yumrepo_core: "puppetlabs/yumrepo_core"
    wget:         "puppet/wget"
    mysql:        "puppetlabs/mysql"
    systemd:      "camptocamp/systemd"
  symlinks:
    artifactory:  "#{source_dir}"
